import { FeatureNavbar } from '@nx-family/feature-navbar';
import { FeatureFooter } from '@nx-family/feature-footer';
import { ThemeProvider } from '@nx-family/shell';

import 'bootstrap/dist/css/bootstrap.min.css';
import 'reset-css';
import './global.scss';

import styles from './layout.module.scss';

export const metadata = {
  title: 'Welcome to family',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
          <link
              rel="manifest"
              href="/manifest.json"
          />
      </head>
      <body>
        <ThemeProvider>
          <div className={styles.layout}>
            <FeatureNavbar />
            <div className={styles.container}>{children}</div>
            <FeatureFooter />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
